Wednus Platform: module/dkernel/xdoc.js File Reference
xdoc.js File Reference
Functions
function XMLDoc (source, errFn)
function _XMLDoc_createXMLNode (strXML)
function _XMLDoc_error (str)
function _XMLDoc_getTagNameParams (tag, obj)
Variables
W x2doc
Convert XML to DocNode.
Function Documentation
function XMLDoc (source, errFn)
Definition at line 13 of file xdoc.js.
References _XMLDoc_createXMLNode(), and _XMLDoc_error().
Referenced by _XMLDoc_createXMLNode().
function _XMLDoc_createXMLNode (strXML)
Definition at line 63 of file xdoc.js.
References XMLDoc().
Referenced by XMLDoc().
function _XMLDoc_error (str)
Definition at line 78 of file xdoc.js.
Referenced by XMLDoc().
function _XMLDoc_getTagNameParams (tag, obj)
Definition at line 99 of file xdoc.js.
Variable Documentation
W x2doc
Initial value:
 function(xml){
    return new XMLDoc(xml).docNode;
}
Convert XML to DocNode.
This function converts a XML string into a docnode.
Parameters:
xml XML string
Returns:
DOM object
Definition at line 8 of file xdoc.js.
we don't use toilet paper; we use our bare hands.